

-- Generated by Relational Schema Center on Mon Oct 01 11:40:59 MSD 2007 for Informix Dynamic Server, V9.4

   
CREATE DATABASE july;

CREATE SCHEMA AUTHORIZATION informix;

CREATE TABLE informix.sequences
  (id CHAR(50) NOT NULL,
   value INTEGER NOT NULL);

ALTER TABLE informix.sequences ADD CONSTRAINT
  (PRIMARY KEY (id) CONSTRAINT pk_sequences);